 // Source code is unavailable, and was generated by the Fernflower decompiler.
 package org.jpc.jspring.enums;

 public enum ResponseCodeEnum {
    SUCCESS(200, false, "Successful"),
    FAILED(400, true, "An error occurred"),
    ERROR_OCCURRED(500, true, "Error occurred"),
    INFOWARE_API_SUCCESS(0, true, "Successful"),
    INFOWARE_API_FAILED(7, true, "Failed"),
    BAD_REQUEST(400, true, "Bad request"),
    NOT_FOUND(404, false, "Record not found"),
    METHOD_NOT_ALOWED(405, true, "Method not allowed"),
    UNSUPPORTED_MEDIA_TYPE(415, true, "Unsupported media type"),
    INTERNAL_SYSTEM_ERROR(500, true, "Server error"),
    SOCKET_TIMEOUT(503, true, "I/O timeout ... Please try again later"),
    SERVICE_UNAVAILABLE(503, true, "Service unavailable");
 
    private int statusCode;
    private boolean hasError;
    private String message;
 
    private ResponseCodeEnum(int statusCode, boolean hasError, String message) {
       this.statusCode = statusCode;
       this.hasError = hasError;
       this.message = message;
    }
 
    public int getStatusCode() {
       return this.statusCode;
    }
 
    public void setStatusCode(final int statusCode) {
       this.statusCode = statusCode;
    }
 
    public boolean isHasError() {
       return this.hasError;
    }
 
    public void setHasError(final boolean hasError) {
       this.hasError = hasError;
    }
 
    public String getMessage() {
       return this.message;
    }
 
    public void setMessage(final String message) {
       this.message = message;
    }
 }
 